name: Deploy VPS AMD Setup

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}
        
    - name: Deploy files to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'mkdir -p ~/vps-setup'
        scp -r -o StrictHostKeyChecking=no ./* ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/vps-setup/
        
    - name: Run installation
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'cd ~/vps-setup && chmod +x *.sh && ./main-install.sh'
